disabled_rules:
  - force_cast
  - type_name
  - trailing_comma
included:
  - Sources
  - Tests
excluded:
  - Sources/Container.Arguments.swift
  - Sources/SynchronizedResolver.Arguments.swift
  - Sources/Resolver.swift
  - Sources/ServiceEntry.TypeForwarding.swift
<<<<<<< HEAD
  - Sample-iOS.playground
  - Carthage
  - Packages
  - Tests
variable_name:
  min_length:
    warning: 1
    error: 1
=======
>>>>>>> upstream/master
